config/routes.rb
Florarails::Application.routes.draw do

  root :to => "catalogo#index"

  resources :clientes
  resources :produtos
  resources :grupos
  
  

  match 'catalogo' => 'catalogo#index' 
  match 'catalogo/detalhes' => 'catalogo#detalhes'
  match 'catalogo/adicionar_no_carrinho/:id' => 'catalogo#adicionar_no_carrinho'
  match 'catalogo/esvaziar_carrinho' => 'catalogo#esvaziar_carrinho'
  match 'catalogo/remover_do_carrinho/:id' => 'catalogo#remover_do_carrinho'
  match 'catalogo/procurar' => 'catalogo#procurar'
  match 'catalogo/lista_itens_grupo' => 'catalogo#lista_itens_grupo'
  match 'pedidos/fechar_pedido' => 'pedidos#fechar_pedido'
  match 'acessos/login' => 'acessos#login'
  match 'acessos/logout' => 'acessos#logout'
  match 'catalogo/salva_pedido' => 'catalogo#salva_pedido'
  
  

end

app/models/cliente.rb
#vamos carregar a biblioteca SHA(Secure Hash #Algoritm)
require 'digest/sha2'
  
class Cliente < ActiveRecord::Base

  has_many :pedido
  accepts_nested_attributes_for :pedido
  
  # O método attr_accessor fornece uma alternativa mais curta, que usar os 
  # métodos attr_reader e attr_writer.
  attr_accessor :senha_confirmation

  # Definindo o método que deverá ser executado antes de salvar o registro
  before_save :criptografa_senha, :limpa_formato_cep

  # Validando os atributos únicos
  validates_uniqueness_of :cpf, :email, :message => ' já foi informado'  

  # Validando os atributos obrigatórios
  validates_presence_of :senha, :senha_confirmation, :nome, :email, :cpf, 
                        :telefone, :message => ' campo é obrigatório'

  # Validando se o campo senha e o senha_confirmation são iguais
  # Por default, o RoR irá procurar por um campo com o nome + _ confirmation
  validates_confirmation_of :senha

  # Validando o tamanho do campo senha
  validates_length_of :senha, :within => 6..20, :too_long => "Informe uma senha menor",
  :too_short => "Informe uma senha maior"

  # Utilizando expressões regulares para validar campos
  validates_format_of :cpf, :with => %r{^(\d{3})\.(\d{3}).(\d{3})-(\d{2})$}i,
                      :message => 'O CPF deve ser digitado no formato: 999.999.99'

  validates_format_of :telefone, :with => %r{^\(\d{2}\)\d{4}-\d{4}$}i,
                      :message => 'O telefone deve ser digitado no formato: (99)9999-9999'

  validates_format_of :email, :with => %r{^[A-Za-z0-9_.-]+@([A-Za-z0-9_]+\.)+[A-Za-z]{2,4}$}i,
                      :message => 'O e-mail informado é inválido'
                      
   validates_format_of :cep, :with => %r{^(\d{5})-(\d{3})$}i,
                      :message => 'O CEP deve ser digitado no formato 99999-99'                      

  # Método para criptografar a senha com SHA
  def criptografa_senha
     self.senha = Digest::SHA256.hexdigest(senha)
  end

  def limpa_formato_cep
    self.cep = cep[0..4] + cep[6..8]
  end
  
  
end

app/controllers/clientes_controller.rb
# OpenURI é um wraper para uilizar http, https e ftp.
# Um wrapper permite que um objeto cliente utilize serviços de outros objetos
# com interfaces diferentes por meio de uma interface única.
  
class ClientesController < ApplicationController

  # Ao invés de utilizarmos o layout padrão, vamos definir outro layout
  layout "catalogo"

  def index
    @clientes = Cliente.find(:all)
  end
  
  
  def destroy
    @clientes = Cliente.find(params[:id])
    @cliente.destroy
    flash[:info] = "Cliente excluido com sucesso"
    redirect_to(clientes_path)
  end
      
  
  def show
    @cliente = Cliente.find(params[:id])
  end


  def new
    @cliente = Cliente.new  
  end


  def create
    @cliente = Cliente.new(params[:cliente])
    respond_to do |format|
      if @cliente.save
        format.html {redirect_to @cliente, :notice => 'Seus dados foram salvos com sucesso!'}
        format.json { render :json => @cliente, :status => :created, :location => @cliente}
      else
        erros = @cliente.errors.full_messages.to_s
        flash[:erro] = 'Erro ao salvar o cliente!' + erros
        format.html{render :action => "new"}
        format.json { render :json => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/index.erb
<h1> Listagem dos clientes </h1>

<table>
  
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>e-mail</th>
    <th>Cidade</th>
    <th>Endereço</th>
    <th>Edição</th>
  </tr>
  
  <%= for cliente in @clientes %>
  
    <tr>
      <td>
        <%=h cliente.id %>
      </td>
      <td<
        <%=h cliente.nome %>
      </td>
      <td>
        <%=h cliente.email %>
      </td>
      <td>
        <%=h cliente.cidade + '/' + cliente.uf %>
      </td>
      <td>
        <%=h cliente.logradouro %>
      </td>
      <td>
        <%= link_to image_tag("pencil_go.png",
                    :border => 0,
                    :title => "Exibir") %>
        <%= link_to image_tag("pencil.png",
                    :border => 0,
                    :title => "Editar"),
                     edit_cliente_path(cliente) %>
        <%= link_to  image_tag("pencil_delete.png",
                     :border => 0,
                     :title => "Apagar",
                     :confirm => "Você tem certeza que deseja apagar o cliente?",
                     :method => :delet %>
      </td>
    </tr>

  <% end %>

</table>

<br/>

<%= link_to image_tag("pencil_add.png",
            :border => 0,
            :title => "Adicionar cliente"),
            new_cliente_path %>
<%= link_to 'Novo Cliente', new_cliente_path %>
            

app/views/clientes/new.html.erb
<%= form_for(@cliente) do |f| %>

<fieldset>

  <legend> Informe seus dados: </legend>

<table>
  <tr>
    <td colspan = "2"> 
      Nome: <br><%= f.text_field :nome, 
                                 :maxlength => 60, 
                                 :size => 50 %> 
    </td>
  </tr>
  
  <tr>
    <td colspan = "2">
      e-mail: <br><%= f.text_field :email,
                                   :maxlength => 60,
                                   :size => 50 %>
    </td>
  </tr>

  <tr>
    <td>
      Senha: <br><%= f.password_field :senha, 
                                      :maxlength => 60,
                                      :size => 20 %>
    </td>
    <td>
      Confirmação da senha: <br><%= f.password_field :senha_confirmation,
                                                     :maxlength => 60,
                                                     :size => 20 %>
    </td>
  </tr>

  <tr>
    <td>
      CPF: 999.999.999-99 <br><%= f.text_field :cpf,
                                               :maxlength => 14,
                                               :size => 14 %>
    </td>
    <td> 
      Telefone: (99)9999-9999 <br><%= f.text_field :telefone,
                                                   :maxlength => 13,
                                                   :size => 13 %>
    </td>
  </tr>

    <td colspan = "2">
      CEP: 99999-999 <br><%= f.text_field :cep,
                                :size => 9,
                                :maxlength => 9 %>
    </td>
                                
  <tr>
    <td> 
      Cidade: <br><%= f.text_field :cidade,                                       
                                   :maxlength => 60,
                                   :size => 20 %>
    </td>
    <td>
      UF: <br><%= f.select :uf,
	                         ['AC', 'AL', 'AP', 'BA', 'CE', 'DF', 'ES', 
	                          'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 
	                          'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 
	                          'RS', 'SC', 'SE', 'SP', 'TO'] %>
    </td>
  </tr>

  <tr>
    <td colspan = "2">
      Endereço: <br> <%=f.text_field :logradouro,
                                     :maxlength => 100,
                                     :size => 50 %>
    <td>
  </tr>

  <tr>
    <td>
      Complemento: <br> <%= f.text_field :complemento,
                                         :maxlength => 20,
                                         :size => 10 %>
    </td>
    <td>
      Bairro: <br><%= f.text_field :bairro,
                                   :maxlength => 60,
                                   :size => 30 %>
    </td>
  </tr>

</table>

</fieldset>

<p>
  <%= f.submit "Gravar" %>
</p>

<% end %>

<%= link_to 'Voltar', catalogo_path %>
                                                                                                                                                                                                   

app/views/clientes/show.erb
<h2>Cliente: <%= @cliente.nome %></h2>

<%= form_for @cliente do |cliente_form| %>

  <h4>
    
    <p>Código: <%= @cliente.id %></p>
    <p>e-mail: <%=h @cliente.email %></p>
    <p>CPF: <%=h @cliente.cpf %></p>
    <p>Telefone: <%=h @cliente.telefone %></p>
    <p>CEP: <%=h @cliente.cep %></p>
    <p>Cidade: <%=h @cliente.cidade %></p>
    <p>UF: <%=h @cliente.uf %></p>
    <p>Endereço: <%=h @cliente.logradouro %></p>
    <p>Complemento: <%=h @cliente.complemento %></p>
    <p>Bairro: <%=h @cliente.bairro %></p>
  
  </h4>
  
  <fieldset>
    
    <legend>Histórico dos Pedidos</legend>
    
    <table>
      
      <tr>
      
        <td width=80 %>Nº dos Pedidos</td>
        <td width=90 %>Emissão</td>
        <td width=280 %>Observação</td>
      
      </tr>
    
        <% @cliente.pedido.each do |pedido| %>
          
           <tr>
           
            <td>
              <%= pedido.id %>
            </td>
            <td>
              <%= pedido.emissao %>
            </td>
            <td>
              <%= pedido.observacao %>
            </td>
            
           </tr>
           
        <% end %>
      
    </table>
    
  </fieldset>
  
<% end %>  