config/routes.rb
Florarails::Application.routes.draw do

  root :to => "catalogo#index"

  resources :clientes
  resources :produtos
  resources :grupos
  
  

  match 'catalogo' => 'catalogo#index' 
  match 'catalogo/detalhes' => 'catalogo#detalhes'
  match 'catalogo/adicionar_no_carrinho/:id' => 'catalogo#adicionar_no_carrinho'
  match 'catalogo/esvaziar_carrinho' => 'catalogo#esvaziar_carrinho'
  match 'catalogo/remover_do_carrinho/:id' => 'catalogo#remover_do_carrinho'
  match 'catalogo/procurar' => 'catalogo#procurar'
  match 'catalogo/lista_itens_grupo' => 'catalogo#lista_itens_grupo'
  match 'pedidos/fechar_pedido' => 'pedidos#fechar_pedido'
  match 'acessos/login' => 'acessos#login'
  match 'acessos/logout' => 'acessos#logout'
  match 'catalogo/salva_pedido' => 'catalogo#salva_pedido'
  
  

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
  default_scope :order => 'id ASC'

  has_many :produto
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  def index
    @grupos = Grupo.find(:all)
  end
  
  def show
    @grupo = Grupo.find(params[:id])
  end

  #instancia um novo objeto
  def new
    @grupo = Grupo.new
  end

  #recebe os parametros do formulario, grava no banco de dados
  #exie uma mensagem para o usuário
  def create 
    @grupo = Grupo.new(params[:grupo])
    if @grupo.save
      flash[:aviso] = 'Grupo salvo com sucesso!'
    else
      flash[:erro] = 'Erro ao salvar o grupo'
    end  
      redirect_to(@grupo)
  end

  #traz os dados do formulário
  def edit
    @grupo = Grupo.find(params[:id])
  end

  #grava efetivamente as alterações no banco de dados 
  def update
    @grupo = Grupo.find(params[:id]) 
    if @grupo.update_attributes(params[:grupo])
      flash[:aviso] = 'Grupo atualizado com sucesso.'
      redirect_to(@grupo)
    end
  end

  #deleta um registro
  def destroy
    @grupo = Grupo.find(params[:id])
    @grupo.destroy
    flash[:info] = "Grupo excluido com sucesso!"
    redirect_to(grupos_path)
  end

end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/grupos/edit.erb
<%= form_for(@grupo) do |form| %>
  <fieldset>
    <legend> Edição do Grupo </legend>
    <p>
      <%= form.label :descricao, "Descrição: " %>
      <%= form.text_field :descricao, :size => 40 %>
  </fieldset>
  <%= form.submit "Alterar" %>
<% end %>

app/views/grupos/index.html.erb
<h1> Listagem dos grupos </h1>
<% for grupo in @grupos %>
  <h2><%= grupo.id %> - <%= link_to grupo.descricao,
            grupo_path(grupo) %></h2>
<% end %>
<p>
<%= link_to 'Cadastrar novo grupo', new_grupo_path %>

app/views/grupos/new.erb
<%= form_for(@grupo) do |form| %>
  <fieldset>
    <legend> Inclusão do Grupo </legend>
    <p>
      <%= form.label :descricao, "Descrição:" %>
      <%= form.text_field :descricao, :size => 40 %>
  </fieldset>
  <%= form.submit "Gravar" %>
<% end %>

app/views/grupos/show.html.erb
<h2> Detalhes do grupo <%= @grupo.descricao %></h2>
<h4>
  <p>Código: <%= @grupo.id%></p>
  <p>Descrição: <%= @grupo.descricao %></p>
  <p>Data do cadastro:
  <%= @grupo.created_at.strftime("%d/%m/%Y %H:%M") %></p>
</h4>
<p>
<%= link_to 'Voltar', grupos_path %>
<%= link_to 'Editar', edit_grupo_path %>
<%= link_to 'Excluir', grupo_path,
      :confirm => 'Confirma a exclusão do regisro?',
      :method => :delete %>