config/routes.rb
Florarails::Application.routes.draw do

  root :to => "catalogo#index"

  resources :clientes
  resources :produtos
  resources :grupos
  
  

  match 'catalogo' => 'catalogo#index' 
  match 'catalogo/detalhes' => 'catalogo#detalhes'
  match 'catalogo/adicionar_no_carrinho/:id' => 'catalogo#adicionar_no_carrinho'
  match 'catalogo/esvaziar_carrinho' => 'catalogo#esvaziar_carrinho'
  match 'catalogo/remover_do_carrinho/:id' => 'catalogo#remover_do_carrinho'
  match 'catalogo/procurar' => 'catalogo#procurar'
  match 'catalogo/lista_itens_grupo' => 'catalogo#lista_itens_grupo'
  match 'pedidos/fechar_pedido' => 'pedidos#fechar_pedido'
  match 'acessos/login' => 'acessos#login'
  match 'acessos/logout' => 'acessos#logout'
  match 'catalogo/salva_pedido' => 'catalogo#salva_pedido'
  
  

end

app/models/produto.rb
require 'paperclip'

class Produto < ActiveRecord::Base

  has_many :itempedido
    belongs_to :grupo

  belongs_to :grupo


  def self.localizar_produto_para_venda
    find(:all, :order => "titulo",
         :conditions => ['validade >=?', Date.current])
  end


  def to_param
    require 'iconv'
    texto = Iconv.iconv("ASCII//IGNORE/TRANSLIT",
    "UTF-8", titulo).join.gsub(/[\s]+/i,
    '_').gsub(/[^a-z0-9\_]+/i,'').downcase
    "#{id}-#{texto}"
  end


  has_attached_file :imagem, 
                    :styles => {:grande => "800x600>",
                                :media => "200x150",
                                :pequena => "80x60",
                                :thumb => "40x30"}

  #obriga o usuário a escolher um arquivo
  validates_attachment_presence :imagem,
    :message => 'Imagem deve ser informada'


  #verifica se o tipo de arquivo está correto
  validates_attachment_content_type :imagem,
    :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/pjpeg'],
    :message => 'Tipo da imagem é inválido!'
    #Validações do modelo
    validates_presence_of :titulo, :descricao
    validates_numericality_of :preco
    validate :preco_deve_ser_no_minimo_um_centavo
    validates_uniqueness_of :titulo

  
  #Método protected indica que o acesso é apenas a objetos da classe e subclasse
  protected

  def preco_deve_ser_no_minimo_um_centavo
    errors.add(:preco, 'deve ser no mínimo 0.01') if preco.nil? || preco < 0.01
  end

  def self.lista_produto_grupo(grupo)
    find(:all, :order => "titulo",
         :conditions => ['validade >= ? and grupo_id = ?', Date.current, grupo])
  end

  
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml
      format.json { render :json => @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, :notice => 'Produto criado com sucesso!' }
        format.json { render :json => @produto, :status => :created, :location => @produto }
      else
        format.html { render :action => "new" }
        format.json { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, :notice => 'Produto alterado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_formproduto.html.erb
<!-- multipart permite realizar uploads de arquivos !-->
<%= form_for(@produto, :html => { :multipart => true }) do |form| %>

  <% if @produto.errors.any? %>
    <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <p> <%= form.label :titulo, "Título" %> </br>
  <%= form.text_field :titulo, :size => 40 %> </p>
  
  <p> <%= form.label :descricao, "Descrição" %> </br>
  <%= form.text_area :descricao, :rows => 6, :cols => 40 %> </p>
  
  <p> <%= form.label :preco, "Valor" %> </br>
  <%= form.text_field :preco, :size => 12 %> </p>

  <p> <%= form.label :validade, "Data de validade" %> </br>
  <%= form.date_select(:validade, :order => [:day, :month, :year],
    :use_month_numbers => true) %> </p>

  <p> <%= form.label :imagem %> </br>
      <%= form.file_field :imagem %> </p>

  <p> <%= form.label :grupo, "Grupo" %> </br>
  <%= form.select :grupo_id, Grupo.find(:all).collect {|gru| [gru.descricao, gru.id] } %>
  </p>

  <p> <%= form.submit "Gravar" %> </p>

<% end %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/edit.html.erb
<fieldset>

  <legend> Edição de Produtos </legend>

  <%= render 'formproduto' %>
  
</fieldset>       

app/views/produtos/index.html.erb
<h1> Listagens do Produto </h1>

<table>
  <tr>
    <th> Titulo </th>
    <th> Imagem </th>
    <th> Descricao </th>
    <th> Preco </th>
    <th> Validade </th>
  </tr>

<% for produto in @produtos %>
  <tr>
  
    <td> <%= produto.titulo %> </td>
    <td> <%= image_tag produto.imagem.url(:pequena) %> </td>
    <td> <%= truncate(produto.descricao, 
            :ommision => "...", :length => 35) %> </td>
            
    <td> <%= numero_em_reais(produto.preco) %> </td>
    
    <td> <%= produto.validade.strftime("%d/%m/%Y") %> </td>
    
    <td> <%= link_to image_tag("pencil_go.png"), produto %>
    
         <%= link_to image_tag("pencil.png"),
             edit_produto_path(produto) %>
             
         <%= link_to image_tag ("pencil_delete.png"), produto, :confirm => 
              'Você tem certeza que deseja apagar o produto?', 
              :method => :delete %> </td>
  </tr>
<% end %> 

</table>

<br />

<%= link_to image_tag("pencil_add.png"), new_produto_path %>
<%= link_to 'Novo Produto', new_produto_path %>

app/views/produtos/index.xml.erb
<% for produto in @produtos %>
    <titulo> <%= produto.titulo %> </titulo>
    <numero_em_reais> <%= numero_em_reais(produto.preco) %> </numero_em_reais>
    <validade> <%= produto.validade.strftime("%d/%m/%Y") %> </validade>
<% end %> 

app/views/produtos/new.html.erb
<fieldset>

  <legend> Inclusão de Produtos </legend>

  <%= render 'formproduto' %>
  
</fieldset>       

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2> Detalhes do produto <%= @produto.titulo %> </h2>
</p>

<h4>

  <p> Código: <%= @produto.id %> </p>
  
  <p> Descricao: <%= @produto.descricao %> </p>

  <p> <%= image_tag @produto.imagem.url(:media) %> </p>

  <p> Valor: <%= @produto.preco %> </p>

  <p> Validade: <%=h @produto.validade.strftime("%d/%m/%Y") %> </p>

  <p> Grupo: <%= @produto.grupo.descricao %> </p>

  <p> Data do Cadastro: <%=h @produto.created_at.strftime("%d/%m/%Y %H:%M") %> </p>

</h4>
<p>

  <%= link_to 'Voltar', produtos_path %>
  <%= link_to 'Editar', edit_produto_path %> 
  <%= link_to 'Excluir', produtos_path,
      :confirm => 'Confirma a exclusão do registro?',
      :method => :delete %>
</p>